### PR TITLE
    Environments Fixups

### PR DESCRIPTION
**Pull request by shapi78**
Creating environment variable in the right order

### CODE REVIEW

**Comment by shapi78** [comment]
Can you please check?

**Comment by shapi78** [comment]
Last time we decided that it would be environment.region.graduway.com - this change is needed to complete it.

**Comment by antgel** [comment]
@shapi78 Okay, so then the tag should be called `env_region`. Please update elsewhere if necessary.

**Comment by shapi78** [comment]
Changed

**Pull request merged**
